import numpy as np

text = [
    ['YPWAIETOAENRMHMGEN', 'MIVWDMKDTCBANGBFKW'],
    ['NQLLWQMIRLVFSDROTN', 'VKIIAAKIRLHADHESVG'],
    ['LINVADMCURYBOFEUAI', 'DRULRHTDEESEBREPYE'],
    ['VRBOOHHSDEWEAANANN', 'EERATOLITEJEPEPZFN'],
    ['ANHIITBICPATELTTMH', 'FEKETCHPMSNAFEWNQM'],
    ['SFTOAINWLXARKLANFE', 'NEWEDSANENTEGQLHUA'],
    ['OENIRSRONOFKGVEKAR', 'TLBGONGUWHILPAFNAS'],
    ['EHERESSOVEMDGJTCWS', 'RDMCORRODAPJNLSAWY'],
    ['TASEWNHEVGRANOKNOT', 'SHTOELHTICUTMLHOIO'],
    ['HRFRONLRATTATTIQAT', 'ANEUOASGNHSFALEHND'],
]


def get_index(letter):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    return alphabet.index(letter)


# letter index to letter
def get_letter(index):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    return alphabet[index]


texts_ = []
for text in texts:
    text1 = [get_index(text) for text in text[0][::-1]]
    text2 = [get_index(text) for text in text[1]]

    text_ = [np.abs(a - b) for a, b in zip(text1, text2)]
    text_ = [get_letter(text) for text in text_]
    text_ = ''.join(text_)
    texts_.append(text_)

for x in texts_:
    print(x)

a = ['CFRBCJTNCPKHAEKPEB', 'HFHHPNMBGGNFSDJGJI', 'HQCRRCIQQNVSHMHARF', 'IMYBKIDJBPOHOTNRJJ', 'MDGOEOBFQDPMCIPJIC',
     'SPMDQCJDCTNRIIEJBJ', 'EEADRDGGGIPEHHCJLC', 'UPEBHFJBVBCOLFRKTB', 'FIEDLBMQTCCHCKEGHB', 'EECNDNGBHGNSTFMMNT']

b = ['MHBWFIJLTCMRBBLBGJ', 'IGDDWQCAAAOFPENECH', 'IJHKREHBQNGDNMAFYE', 'RNQOFHEKQANAPECZIA', 'FJDELRGHKDNTBHDGEF',
     'FBDKDKNJHKTNEFLGPE', 'FHMCDFLGJHDBJVBDAB', 'NEIPKBBASEDGHCBCAG', 'BHBKSCAPNEDTBDDBGF', 'HEBDANHLNMBFTIEJNQ']

c = ['BEPKEAHKPCNTJCBRFC', 'IJGJDSFNGGBMNPHHFH', 'FRAHMHSVNQQICRRCQH', 'JJRNTOHOPBJDIKBYMI', 'CIJPICMPDQFBOEOGDM',
     'JBJEIIRNTCDJCQDMPS', 'CLJCHHEPIGGGDRDAEE', 'BTKRFLOCBVBJFHBEPU', 'BHGEKCHCCTQMBLDEIF', 'TNMMFTSNGHBGNDNCEE']
